server:
  address: 202.116.105.13
  port: 10010

logging:
  level:
    com.oncoit: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://202.116.105.13:3306/ONCOIT
    username: root
    password: Sysu-123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.oncoit.pojo

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl